/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package painel.venda.formaspagamento;

import dados.BancoDados;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import utilitarias.classes.Produto;
import utilitarias.classes.Venda;
import utilitarias.sistema.CampoMoedaFormatada;
import utilitarias.sistema.ControleAtalhos;

/**
 *
 * @author samuel
 */
public class PainelPagamentoDinheiro extends javax.swing.JDialog {

    /**
     * Creates new form PainelPagamentoDinheiro
     */
    HashMap<String, Produto> listaProdutoshasMap = BancoDados.getHashmapProdutos();
    HashMap<String, Produto> listaCarrinhohashMap = BancoDados.getHashmapCarrinho();
    Venda venda;
    
    public PainelPagamentoDinheiro(JFrame parent, Venda venda) {
        super(parent, true);
        initComponents();
        
        setLocationRelativeTo(null);
        jtValortotal.setText(venda.getValorTotal());
        
        CampoMoedaFormatada.aplicarFormatoMoeda(jtValorRecebido);
        jtValorRecebido.requestFocus();
        
        ControleAtalhos.addKeyBinding(getRootPane(), "F1", () -> {
            for(Produto carrinho: listaCarrinhohashMap.values()) {
                Produto produto = listaProdutoshasMap.get(carrinho.getCodigo());
                produto.setQuatidade(produto.getQuatidade() - carrinho.getQuatidade());
                listaProdutoshasMap.put(carrinho.getCodigo(), produto);
            }
            this.venda.setTipoDePagamento("Dinheiro");
            this.venda.setData();
            listaCarrinhohashMap.clear();
            dispose();
        });
        
        ControleAtalhos.addKeyBinding(getRootPane(), "F2", () -> dispose());
    }
    
    private void calcularValorDevolver() {
        double valorTotal = CampoMoedaFormatada.desformatarFormatoMoeda(jtValortotal.getText());
        double valorRecebido = CampoMoedaFormatada.desformatarFormatoMoeda(jtValorRecebido.getText()); 
        if(valorRecebido < 0) {
            JOptionPane.showMessageDialog(null, "Informe valores Positivos no campo de Recebimento!");
        } else {
            double valorDevolver = valorRecebido - valorTotal;
            if(valorDevolver < 0) {
                jtValorDevolver.setText(CampoMoedaFormatada.formantarValor(Math.abs(valorDevolver)));
                jtValorDevolver.setForeground(Color.RED);
            } else if(valorDevolver > 0) {
                jtValorDevolver.setText(CampoMoedaFormatada.formantarValor(valorDevolver));
                jtValorDevolver.setForeground(new Color(51,102,0));
            } else {
                jtValorDevolver.setText(CampoMoedaFormatada.formantarValor(valorDevolver));
                jtValorDevolver.setForeground(Color.GRAY);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jtValortotal = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jtValorRecebido = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jtValorDevolver = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pagamento Dinheiro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 69));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel22.setToolTipText("");
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtValortotal.setEditable(false);
        jtValortotal.setBackground(new java.awt.Color(255, 255, 255));
        jtValortotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtValortotal.setForeground(new java.awt.Color(51, 102, 0));
        jtValortotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtValortotal.setText("R$ 0,00");
        jtValortotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel22.add(jtValortotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 70));

        jPanel15.setBackground(new java.awt.Color(102, 153, 0));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Valor Total da Compra");
        jPanel15.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 40));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 710, -1));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel23.setToolTipText("");
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtValorRecebido.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtValorRecebido.setForeground(new java.awt.Color(51, 102, 0));
        jtValorRecebido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtValorRecebido.setText("R$ 0,00");
        jtValorRecebido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtValorRecebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtValorRecebidoActionPerformed(evt);
            }
        });
        jPanel23.add(jtValorRecebido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 70));

        jPanel16.setBackground(new java.awt.Color(102, 153, 0));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(102, 153, 0));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Recebido");
        jPanel16.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 40));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 710, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel24.setToolTipText("");
        jPanel24.setPreferredSize(new java.awt.Dimension(700, 90));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtValorDevolver.setEditable(false);
        jtValorDevolver.setBackground(new java.awt.Color(255, 255, 255));
        jtValorDevolver.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jtValorDevolver.setForeground(new java.awt.Color(51, 102, 0));
        jtValorDevolver.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtValorDevolver.setText("R$ 0,00");
        jtValorDevolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel24.add(jtValorDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 98));

        jPanel5.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 710, 98));

        jPanel17.setBackground(new java.awt.Color(51, 102, 0));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Devolver");
        jPanel17.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 40));

        jPanel5.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 710, 140));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 859, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtValorRecebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtValorRecebidoActionPerformed
        calcularValorDevolver();
    }//GEN-LAST:event_jtValorRecebidoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jtValorDevolver;
    private javax.swing.JTextField jtValorRecebido;
    private javax.swing.JTextField jtValortotal;
    // End of variables declaration//GEN-END:variables
}
